# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/nasms_db
spring.datasource.username=postgres
spring.datasource.password=8448
spring.datasource.driver-class-name=org.postgresql.Driver
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


# Server
server.port=8086

# Weather API
weather.api.base-url=https://api.openweathermap.org/data/2.5
weather.api.key=028a80a6a1930f400b3f4b48100cf33c
weather.api.units=metric

# JWT
jwt.secret=yHr2cS5FBJTck+ZBoYNIjPWIKu3WwkrHkvuvwMe5Tts=
jwt.expiration=86400000