spring.application.name=NASMS
spring.datasource.url=jdbc:postgresql://localhost:5432/NASMS_db
spring.datasource.username=postgres
spring.datasource.password=8448
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=w4KjF1h9pS+2s8zVdGqv7Q9nXH8Y2LbPZmZtJv2aZlE=
jwt.expiration=3600000
weather.api.key=YOUR_API_KEY
weather.api.url=https://api.openweathermap.org/data/2.5/weather
weather.api.units=metric



