package com.Farm.NASMS;

public enum CropProduct {
    //cereals
    MAIZE, WHEAT, SORGHUM, OATS, RICE, MILLET, BARLEY,
    //Legumes
    BEANS,LENTILS,PEAS,CHICKPEAS,SOYBEAN,GROUNDNUT,
    //TUBER CROPS
    POTATO,SWEET_POTATO,CASSAVA,YAM,CARROT,BEETROOT,
    //VEGETABLES
    TOMATO,ONION,CABBAGE,SPINACH,LETTUCE,PEPPER,EGGPLANT,
    //FRUITS
    MANGO,BANANA,OVACADO,ORANGE,APPLE,WATERMELON,PAWPAW,
    //CASH CROPS
    COFFEE,TEA,COTTON,SUGAR_CANE,TOBACCO,OIL_PALM;


}
